### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by ericdrosado** [Codehackerone/parkify#3]
👋 Hi @Codehackerone ,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Learn + Collaborate` repo. This means that you would like to teach students, step by step, how to build this project as well as invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a `Learn + Collaborate` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you :octocat: 

## Issues
- [x] https://github.com/Codehackerone/parkify/issues/4
- [x] https://github.com/Codehackerone/parkify/issues/5
- [x] https://github.com/Codehackerone/parkify/issues/6
- [x] https://github.com/Codehackerone/parkify/issues/7
- [x] https://github.com/Codehackerone/parkify/issues/8
- [x] https://github.com/Codehackerone/parkify/issues/9
- [x] https://github.com/Codehackerone/parkify/issues/10

**Comment by Codehackerone** [comment]
Hey @ericdrosado, 
First of all, I am super excited to collaborate with GitHub for CX Program. I'll start working on the issues right away, and I'll proceed with the steps that you mentioned. One quick question, should this issue be private?

**Comment by ericdrosado** [comment]
> should this issue be private?

These issues can remain public. 😄

**Comment by Codehackerone** [comment]
Hi. I have issued 2 PRs. Can you please review it? I have also added you to the repo.

**Comment by Codehackerone** [comment]
@ericdrosado After this is ready for CX 'collaborate' can I start making LEARN.md for 'learn' repo?

**Comment by ericdrosado** [comment]
> After this is ready for CX 'collaborate' can I start making LEARN.md for 'learn' repo?

Sure, you are more than welcome to do so after.

**Comment by Codehackerone** [comment]
All issues completed.

**Comment by ericdrosado** [comment]
Excellent @Codehackerone! 🎉  I will contact you next week with next steps on how to submit your repository.

**Comment by Codehackerone** [comment]
Hi @ericdrosado!! Any updates?

**Comment by ericdrosado** [comment]
👋 Hey @Codehackerone ! I'll post a comment here, June 1st at the latest. 😄

**Comment by Codehackerone** [comment]
Hi, @ericdrosado, I have done some readme changes, can you review the pr?

**Comment by Codehackerone** [comment]
Hi, @ericdrosado. Can I add this under my list of achievements to my LinkedIn profile? If yes, what would be the title for it?

**Comment by ericdrosado** [comment]
> Can I add this under my list of achievements to my LinkedIn profile?

I don't see why you couldn't. I would add it as a `Project` and  link to your repo. You could title it as: "Private beta user of GitHub Education Community Exchange."

You can link your repo URL and provide a description of what you did.
